version: "1"

log_level: "info"
listen_addr: "0.0.0.0:8080"
introspection_enabled: true
json_log: true

headers:
  all:
    request:
      - op: 'propagate'
        matching: .*

cors:
  allow_origins: ['*']
  allow_methods:
    - HEAD
    - GET
    - POST
  allow_headers:
    - Origin
    - Content-Length
    - Content-Type
  allow_credentials: true
  max_age_minutes: 5m

include_subgraph_errors:
  all: ${env.INCLUDE_SUBGRAPH_ERRORS:-false}
  
events:
  sources:
    - provider: NATS
      url: 'nats://0.0.0.0:4222'

engine:
  debug:
    report_websocket_connections: true